import { defineStore } from "pinia";
import { getTimetable } from "@/service/user/index";

interface infoType {
  courseId: string;
  courseUserId: number;
  courseWeek: number;
  courseName: string;
  courseOrder: number;
  courseBeginDate: string;
  courseEndDate: string;
  courseIsDouble: boolean;
  courseIsDelete: boolean;
}

// type DayOfWeek =
//   | "monday"
//   | "tuesday"
//   | "wednesday"
//   | "thursday"
//   | "friday"
//   | "saturday"
//   | "sunday";
type DayOfWeek = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const useCourseStore = defineStore("course", {
  state: () => ({
    courseList: [
      [
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 0,
          courseName: "高数",
          courseOrder: 1,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 1,
          courseName: "数据结构",
          courseOrder: 1,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        // {
        //   courseId: 10,
        //   courseUserId: 4,
        //   courseWeek: 2,
        //   courseName: "英语",
        //   courseOrder: 1,
        //   courseBeginDate: "2023-11-10",
        //   courseEndDate: "2023-12-10",
        //   courseIsDouble: false,
        //   courseIsDelete: false,
        // },
        {
          courseId: 10,
          courseUserId: 3,
          courseWeek: 3,
          courseName: "高数",
          courseOrder: 1,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 4,
          courseName: "高数",
          courseOrder: 1,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        // {
        //   courseId: 10,
        //   courseUserId: 4,
        //   courseWeek: 5,
        //   courseName: "高数",
        //   courseOrder: 1,
        //   courseBeginDate: "2023-11-10",
        //   courseEndDate: "2023-12-10",
        //   courseIsDouble: false,
        //   courseIsDelete: false,
        // },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 6,
          courseName: "高数",
          courseOrder: 1,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
      ],
      [
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 0,
          courseName: "高数",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 1,
          courseName: "高数",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 2,
          courseName: "英语",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 3,
          courseWeek: 3,
          courseName: "c",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 4,
          courseName: "java",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 5,
          courseName: "高数",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 6,
          courseName: "高数",
          courseOrder: 2,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
      ],
      [
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 0,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 1,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 2,
          courseName: "英语",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 3,
          courseWeek: 3,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 4,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 5,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 6,
          courseName: "高数",
          courseOrder: 3,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
      ],
      [
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 0,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 1,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 2,
          courseName: "英语",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 3,
          courseWeek: 3,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 4,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 5,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 6,
          courseName: "高数",
          courseOrder: 4,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
      ],
      [
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 0,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 1,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 2,
          courseName: "英语",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 3,
          courseWeek: 3,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 4,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 5,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
        {
          courseId: 10,
          courseUserId: 4,
          courseWeek: 6,
          courseName: "高数",
          courseOrder: 5,
          courseBeginDate: "2023-11-10",
          courseEndDate: "2023-12-10",
          courseIsDouble: false,
          courseIsDelete: false,
        },
      ],
    ],
  }),

  actions: {
    editCourse(info: infoType, courseOrder: number, courseWeek: string) {
      // this.courseList[courseOrder][courseWeek] = info;
      console.log(info);
      console.log(courseOrder);
      console.log(courseWeek);
    },
  },
});
