export const FileType = {
  gif: "icon-gif",
  mkv: "icon-mkv",
  rar: "icon-rar",
  pdf: "icon-PDF",
  docx: "icon-docx",
  ppt: "icon-ppt",
  zip: "icon-zip",
  exe: "icon-exe",
  doc: "icon-DOC",
  jpg: "icon-JPG",
  png: "icon-PNG",
  html: "icon-HTML",
  xlsx: "icon-xlsx",
  mp4: "icon-MP4",
  "7z": "icon-a-7z",
  other: "icon-OTHER",
  txt: "icon-format-txt",
  yml: "icon-YML",
  js: "icon-js",
  css: "icon-CSS",
};
